export const LanguageObject = {
        'DeleteSelected': 'Delete Selected',
        'Name': 'Name',
        'Description': 'Description',
        'Cost': 'Cost',
        'Nights': 'Nº of Nights',
        'Days': 'Days',
        'Back': 'Back',
        'NotificationEmail': 'Notification Email',
        'Per Night or Per Stay': 'Per Night or Per Stay',
        'Per Room or Per Person': 'Per Room or Per Person',
        'invalidEmail': 'format is invalid',
        'Category': 'Other Policy Category',
        'Type': 'Type',
        'Discount': 'Discount',
        'Anticipation Days': 'Anticipation Days',
        'Anticipation Hours': 'Anticipation Hours',
        'FreeDays': 'Free Days',
        'Minimum Night': 'Minimum Night',
        'Maximum Night': 'Maximum Night',
        'Day': 'Day',
        'MinAge': 'Min Age',
        'MaxAge': 'Max Age',
        'ChargeAs': 'Charge Children group as',
        'commonName': 'Name',
        'commonDescription': 'Description',
        'commonDepositAmount': 'Deposit Amount',
        'commonDepositUpTo': 'Deposit Up To',
        'commonDeposit Up To': 'Deposit Up To',
        'commonDays': 'Days',
        'commonCost': 'Cost',
        'commonNoOfNights': 'No of Nights',
        'commonNo of Nights': 'No of Nights',
        'commonPrefferDate': 'Day(s) prior to Arrival Date',
        'commonDay(s) prior to Arrival Date': 'Day(s) prior to Arrival Date',
        'commonGDPolicies': 'Guarantee / Deposit Policies',
        'commonRemovedGDPolicies': 'Removed Guarantee / Deposit Policies',
        'commonGDPolicy': 'Guarantee / Deposit Policy',
        'commonChainDetails': 'New Chain',
        'commonChains': 'Chains',
        'commonRemovedChains': 'Removed Chains',
        'commonMainDetails': 'Main Details',
        'commonDetails': 'Details',
        'commonGuaranteeType': 'Guarantee Type',
        'commonDepositConditions': 'Deposit Conditions',
        'commonApplyDepositAmount': 'Apply Deposit Amount',
        'commonNumberOfNights': 'Number of Nights',
        'commonGeneralPolicies': 'General Policies',
        'commonRemovedGeneralPolicies': 'Removed General Policies',
        'commonGeneralPolicy': 'General Policy',
        'commonOtherPolicyCategory': 'Other Policy Category',
        'commonAdd': 'Add',
        'commonList': 'List',
        'commonAddCategory': 'Add Category',
        'commonActions': 'Actions',
        'commonCategoriesList': 'Categories List',
        'commonCancellationPolicies': 'Cancellation Policies',
        'commonRemovedCancellationPolicies': 'Removed Cancellation Policies',
        'commonCancellationCosts': 'Cancellation Costs',
        'commonCancellationUpTo': 'Cancellation Up To',
        'commonCancellation Up To': 'Cancellation Up To',
        'commonCancellationPolicy': 'Cancellation Policy',
        'commonCancellationConditions': 'Cancellation Conditions',
        'commonAllowsCancellation': 'Allows Cancellation',
        'commonCancellationCost': 'Cancellation Cost',
        'commonTaxPolicies': 'Tax Policies',
        'commonRemovedTaxPolicies': 'Removed Tax Policies',
        'commonValue': 'Value',
        'commonTaxPolicy': 'Tax Policy',
        'commonBillingType': 'Billing Type',
        'commonPerNightPerStay': 'Per Night or Per Stay',
        'commonPerNight': 'Per Night',
        'commonPerStay': 'Per Stay',
        'commonPerRoomPerPerson': 'Per Room or Per Person',
        'commonPerRoom': 'Per Room',
        'commonPerPerson': 'Per Person',
        'commonTaxValue': 'Tax Value',
        'commonPromotionalSpecialOffers': 'Promotional / Special Offers',
        'commonRemovedPromotionalSpecialOffers': 'Removed Promotional / Special Offers',
        'commonType': 'Type',
        'commonFreeDays': 'Free Days',
        'commonFree Days': 'Free Days',
        'commonDiscount': 'Discount',
        'commonEarlyBooking': 'Early Booking',
        'commonLastMinuteBooking': 'Last Minute Booking',
        'commonFreeNights': 'Free nights',
        'commonStayDiscount': 'Stay Discount',
        'commonHours': 'Hours',
        'commonHoursTerm': 'The reference time is 23h59 of the Check-in day',
        'commonAnticipationOfIncentive': 'Anticipation of Incentive',
        'commonAnticipationIn': 'Anticipation in',
        'commonFreeDaysAre': 'Free days are',
        'commonAtBeginning': 'At the beginning',
        'commonAtEnd': 'At the end',
        'commonMinNight': 'Nr of Minimum Nights',
        'commonMaxNight': 'Nr of Maximum Nights',
        'commonBetweenNight': 'Between Nights',
        'commonNOfNights': 'N of Nights',
        'commonChildTerms': 'Child Terms',
        'commonRemovedChildTerms': 'Removed Child Terms',
        'commonMinAge': 'Min. Age',
        'commonMin. Age': 'Min. Age',
        'commonMaxAge': 'Max. Age',
        'commonMax. Age': 'Max. Age',
        'commonChargeAs': 'Charge As',
        'commonCharge As': 'Charge As',
        'commonPriceVariation': 'Price Variation',
        'commonPrice Variation': 'Price Variation',
        'commonChargeChildrengroupAs': 'Charge Children group as',
        'commonChild': 'Child',
        'commonFree': 'Free',
        'commonAdult': 'Adult',
        'commonActivatePriceVariation': 'Activate Price Variation',
        'commonChildTermsContent': 'By Activating the price variation for children, you will define an amount or percentage that will be applied to the price defined for children in the Update Rates & Availability option.',
        'commonCountsForOccupancy': 'Counts for Occupancy',
        'commonCountsForGeneralOccupancy': 'Children counts for general room occupation.',
        'commonExtras': 'Extras',
        'removedExtras': 'Removed Extras',
        'commonBoardType': 'Board Type',
        'commonBoard Type': 'Board Type',
        'commonStatus': 'Status',
        'commonNotificationEmail': 'Notification E-mail',
        'commonExtraContent': 'Service or person to be notified automatically in case the extra is included in any reservation made through the Booking Engine',
        'commonExtraBoardType': 'This Extra is Board Type',
        'commonBreakfast': 'Breakfast',
        'commonHalfBoard': 'Half board',
        'commonFullBoard': 'Full board',
        'commonAllInclusive': 'All inclusive',
        'commonSettings': 'Settings',
        'commonPhotos': 'Photos',
        'commonUploadPhotos': 'Upload Photos',
        'commonDownload': 'Download',
        'commonPotoSelected': 'photo selected',
        'commonSelectAll': 'Select All',
        'commonClearSelection': 'Clear Selection',
        'commonImageTypePrefrence': 'Use the button Upload Picture or place here your items (+.jpg or *.png)',
        'commonImageTypePrefrencePt1': 'Use the button',
        'commonImageTypePrefrencePt2': 'Upload Picture',
        'commonImageTypePrefrencePt3': 'or place here your items (+.jpg or *.png)',
        'commonRoomTypes': 'Room Types',
        'commonRemovedRoomTypes': 'Removed Room Types',
        'commonPricingLimits': 'Pricing Limits',
        'commonMinPrice': 'Min. Price',
        'commonMaxPrice': 'Max. Price',
        'commonAdultMaxMin.': 'Adult Max/Min.',
        'commonMaxChildren.': 'Max Children',
        'commonExtraBed': 'Extra Bed',
        'commonQuantity': 'Quantity',
        'commonRooms.': 'Rooms',
        'commonShare.': 'Share',
        'commonBookingEngineURL.': 'Booking Engine URL',
        'commonFacebook': 'Facebook',
        'commonGoogle': 'Google+',
        'commonLinkedin': 'Linkedin',
        'commonTwitter': 'Twitter',
        'commonEmail': 'E-mail',
        'email': 'E-mail',
        'phone': 'Phone',
        'commonGetLink': 'Get Link',
        'commonPreview': 'Preview',
        'commonOccupancyInformation': 'Occupancy Information',
        'commonMinPriceLimit': 'Min. Price Limit',
        'commonMaxPriceLimit': 'Max. Price Limit',
        'commonNoOfRooms': 'No. of Rooms',
        'commonMaxPax': 'Max. Pax.',
        'commonMinAdults': 'Min. Adults',
        'commonMaxAdults': 'Max. Adults',
        'commonAcceptExtraBed': 'Accept Extra Bed',
        'commonAcceptChildren': 'Accept Children',
        'commonMaxChild': 'Max. Child',
        'commonMaxFreeChild': 'Max. Free Child',
        'commonAmenities': 'Amenities',
        'commonAdditionalSettings': 'Additional Settings',
        'commonTypeOfBed': 'Type of Bed',
        'commonCategory': 'Category',
        'validationIsRequired': 'is required', // new
        'validationBetweenValue': 'must be between the values {1} and {2}.',
        'commonAnd': 'and',
        'validationLessThen': 'must be less than',
        'validationGreaterThen': 'must be greater than',
        'validationEqualTo': 'must be equal than',
        'validationLessOrEqual': 'must be less or equal than',
        'validationGreaterOrEqual': 'must be greater or equal than',
        'validationFormError': 'Error(s) on your form!',
        'commonExtraValue': 'Extra Value',
        'commonClose': 'Close',
        'commonDefineMain': 'Define as main',
        'commonDisableMain': 'Disable from main',
        'commonNrMinimumNights': 'Nr minimum of Nights',
        'commonNrMaximumNights': 'Nr maximum of Nights',
        'commonRefreshPage': 'Refresh Page?',
        'commonChangesLost': 'All unsaved changes will be lost.',
        'commonNotWarnAgain': 'Do not warn again',
        'commonNotRecordAvailable': 'No records available.',
        'commonUser': 'Users',
        'commonFirst Name': 'First Name',
        'fname': 'First Name',
        'commonLast Name': 'Last Name',
        'uname': 'User Name',
        'upassword': 'User Password',
        'repassword': 'Repeat Password',
        'commonPassword Expiry Date': 'Password Expiry Date',
        'commonPassword Expiry': 'Password Expiry',
        'listRemoveDate': 'Removed Date',
        'listActual': 'Actual', // continue
        'listRemove': 'Removed',
        'listSearch': 'Search',
        'commonSearch': 'Search',
        'listSearchResult': 'Search Result',
        'listClearSearch': 'Clear Search',
        'listFound': 'found',
        'listUpdating': 'Updating',
        'listAddFavorites': 'Add to Favorites',
        'listRemoveFavorites': 'Remove from Favorites',
        'listClearfilters': 'Clear Filters',
        'commonClear Filters': 'Clear Filters',
        'listClearfilter': 'Clear filter',
        'listFilters': 'Filters',
        'listCreateNew': 'Create New', // Add New same translation.
        'listExport': 'Export',
        'listEdit': 'Edit',
        'listDelete': 'Delete',
        'listView': 'View',
        'listExternal': 'Item created on an external systems ',
        'listExternalNotSelected': 'External Items can not be selected',
        'listCollapse': 'Collapse',
        'listExpand': 'Expand',
        'commonChangeHistory': 'Change History',
        'commonMoreOptions': 'More Options',
        'commonYes': 'Yes',
        'commonNo': 'No',
        'commonRefresh': 'Refresh',
        'listOf': 'of',
        'formOtherCurrencies': 'Other Currencies',
        'formTranslate': 'Translate',
        'formTranslateAutomatically': 'Translate Automatically',
        'formSave': 'Save',
        'formCancel': 'Cancel',
        'formOk': 'Ok',
        'commonDeleteNotification': 'Deleted Successfully!',
        'commonSaveNotification': 'Item Saved Successfully!',
        'commonActive': 'Active',
        'commonInactive': 'Inactive',
        'commonHome': 'Home',
        'commonSelect': 'Select',
        'commonPleaseSelect': 'Please Select',
        'commonPhotosSelected': 'Photos Selected',
        'commonSinglePhotoSelected': 'Photo Selected',
        'Afghanistan Afghani': 'Afghanistan Afghani',
        'Argentina Peso': 'Argentina Peso',
        'Euro': 'Euro',
        'commonClient': 'Client',
        'selectRolePermissions': 'Select Role Permissions',
        'Minimum-Night': 'Minimum-Night',
        'Maximum-Night': 'Maximum-Night',
        'commonRoles': 'Roles',
        'removedRoles': 'Removed Roles',
        'commonClientId': 'ClientId',
        'commonNewRole': 'New Role',
        'commonNew': 'New',
        'commonRole': 'Role',
        'Property': 'Property',
        'Contacts': 'Contacts',
        'Roles': 'Roles',
        'Confirmation': 'Confirmation',
        'BaseLanguage': 'Base Language',
        'BaseCurrency': 'Base Currency',
        'GPS': 'GPS',
        'sameAsCompany': 'Same as Company',
        'vatNo': 'Vat No',
        'type': 'Type',
        'AddNew': 'Add New',
        'firstName': 'First Name',
        'lastName': 'Last Name',
        'birthdate': 'Birth Date',
        'category': 'Category',
        'user': 'User',
        'repeatPassword': 'Repeat Password',
        'passwordExpiry': 'Password Expiry',
        'PropertyMainDetails': 'property Main Details',
        'propertyAddress': 'Property Address',
        'pickAddressfromMap': 'Pick Address from Map',
        'creditCards': 'CreditCards',
        'search': 'Search',
        'listOfAccountManagers': 'List of Account Manager',
        'assignedAccManager': 'Assigned Acc Manager',
        'resume': 'Resume',
        'Client': 'Client',
        'Chain': 'Chain',
        'invoicing': 'Invocing',
        'users': 'Users',
        'twoFactorAuthen': 'Two Factor Authen',
        'Propertycreatedsuccessfully': 'Property Created Successfully',
        'YoucannowmanagethepropertyatOmnibees': 'You can now Manage the Property At Omnibees',
        'numOfHotel': 'No. Of Hotels',
        'numberOfHotel': 'NUMBER OF HOTELS',
        'inactivateProperty': 'Inactivate Property',
        'statusHistory': 'Status History',
        'comments': 'Comments',
        'newClient': 'New Client',
        'clientName': 'Client Name',
        'companyName': 'Company Name',
        'country': 'Country',
        'address': 'Address',
        'number': 'Number',
        'state': 'State',
        'city': 'City',
        'postalCode': 'Postal Code',
        'contacts': 'Contacts',
        'mobilePhone': 'Mobile Phone',
        'website': 'Website',
        'contactPerson': 'Contact Person',
        'clientLogotype': 'Client Logotype',
        'uploadLogo': 'Upload logo',
        'logoType': 'type of files: *.jpg or *.png',
        'removeImage': 'Remove Image',
        'listOfChains': 'List of Chains',
        'noRecord': 'No matched record found.',
        'assignedChains': 'Assigned Chains',
        'removeSelected': 'Remove Selected',
        'property': 'Property',
        'Invoicing': 'Invoicing',
        'User': 'User',
        'accManagers': 'Acc. Managers',
        'confirmation': 'Confirmation',
        'clientMainDetails': 'Client Main Details',
        'step': 'Step',
        'of': 'of',
        'No of hotels': 'Nº of Hotels',
        'commonNo of Hotels': 'Nº of Hotels',
        'VAT NO': 'VAT NO',
        'propertyMainDetails': 'Property Main Details',
        'currency': 'Currency',
        'TimeZone': 'Time Zone',
        'PropertyCategory': 'Property Category',
        'TotalRooms': 'Total Rooms',
        'commonTotal Rooms': 'Total Rooms',
        'childrenAllowed': 'Children Allowed',
        'Classification': 'Classification',
        'stars': 'Stars',
        'mapAddress': 'Pick Address from Map',
        'latitude': 'Latitude',
        'longitude': 'Longitude',
        'invoicingDetails': 'Invoicing Details',
        'sameCompany': 'Same as company',
        'propertyName': 'Property Name',
        'userMainDetails': 'User Main Details',
        'prefix': 'Prefix',
        'birthDate': 'Birth Date',
        'cardView': 'Number of Credit Card views',
        'timesIn': 'Times in',
        'minutes': 'minutes',
        'password': 'Password',
        'twoFactorAuthentication': 'Two Factor Authentication',
        'lockedUser': 'Locked User',
        'userRoles': 'User Roles',
        'listofRoles': 'List of Roles',
        'assignedRoles': 'Assigned Roles',
        'accountManagers': 'Account Managers',
        'removedAccountManagers': 'Removed Account Managers',
        'listAccountManagers': 'List of Account Managers',
        'assignedAccountManagers': 'Assigned Account Managers',
        'resumeConfirmation': 'Resume & confirmation',
        'CCView': 'Number of CC. Views',
        'noRoleAssign': 'No Roles have been assigned',
        'assignedAccManagers': 'Assigned Acc. Managers',
        'noAccAssign': 'No Account Managers have been assigned',
        'clientCreate': 'Client created successfully',
        'mangeClient': 'You can now manage the client at',
        'createClient': 'Create New Client',
        'finish': 'Finish',
        'previous': 'Previous',
        'next': 'Next',
        'useAddress': 'Use Address',
        'useCoordinates': 'Use GPS Coordinates',
        'updateRateslabel': 'Update Rates/Packages & Availability',
        'backtoEditor': 'Back to Editor',
        'andmore': 'and more...',
        'dates': 'Dates',
        'addPeriods': 'Add Periods',
        'ratesPackages': 'Rates & Packages',
        'noRateAdded': 'No Rate added.',
        'addRatesPackages': 'Add rates & packages',
        'noRoomTypesAdded': 'No room types added',
        'addRoomType': 'Add room types',
        'roomPrices': 'Room Prices',
        'rateRestrictions': 'Rate Restrictions',
        'closeOpenSales': 'Close/Open Sales',
        'warning': 'Warning',
        'fixedPrice': 'Preço fixo',
        'priceVariation': 'Price Variation',
        'setPriceVariation': 'Set Price Variation',
        'setWeekdays': 'Set Weekdays',
        'baseRoom': '(Base Room)',
        'applyRoomTypeDependency': 'Apply Room Type Dependency',
        'Remove': 'Remove',
        'minimumDays': 'Minimum Days',
        'commonPromoCode': 'Promotional Codes',
        'discountValue': 'Discount Value',
        'availableFor': 'Available For',
        'newPromoCode': 'New Promotional Code',
        'moreOptions': 'More Options',
        'changeHistory': 'Change History',
        'commonRatesAndPackages': 'Rates & Packages',
        'commonCode': 'Code',
        'rolePermissions': 'ROLE PERMISSIONS',
        'All': 'ALL',
        'Read': 'READ',
        'Add': 'ADD',
        'Update': 'UPDATE',
        'Delete': 'DELETE',
        'Execute': 'EXECUTE',
        'client': 'client',
        'baseLanguage': 'Base Language',
        'baseCurrency': 'Base Currency',
        'ChildrensAllowed': 'Childrens Allowed',
        'DemoHotel': 'Demo Hotel',
        'propertyAddressContacts': 'Property Address & Contacts',
        'zone': 'Zone',
        'chain': 'Chain',
        'selectExistingUser': 'Select Existing User',
        'listOfUsers': 'List of Users',
        'assignedUsers': 'Assigned Users',
        'assignedAccountManager': 'Assigned Account Manager',
        'accountManager': 'Account Manager',
        'noRolesAvailable': 'No Roles Available',
        'propertyCreatedSuccessfully': 'Property created successfully',
        'manageProperty': 'You can now manage the property at',
        'CreateNewProperty': 'Create New Property',
        'newUser': 'New User',
        'newAccountManager': 'New Account Manager',
        'commonId': 'Id',
        'newRegisteryCode': 'New Registry Code',
        'changePropertyAssignment': 'Change Property Assignment',
        'replicateProperty': 'Replicate Property',
        'commonCause': 'Cause',
        'activateProperty': 'Activate Property',
        'newProperty': 'New Property',
        'otherInfo': 'Other Info',
        'comapny': 'Company',
        'emailAcc': 'E-mail Acc',
        'propertyLogoType': 'Property Logotype',
        'language': 'Language',
        'otherClassification': 'Other Classification',
        'diamonds': 'Diamonds',
        'otherInformation': 'Other Information',
        'travelDirections': 'Travel Directions',
        'generalManager': 'General Manager',
        'reservations': 'Reservations',
        'schedules': 'Schedules',
        'checkInHours': 'Check-In Hours',
        'checkIn': 'Check-In',
        'checkOut': 'Check-Out',
        'reception': 'Reception',
        'from': 'From',
        'to': 'To',
        'additionalWorkingHours': 'Additional Working Hours',
        'buildYear': 'Build Year',
        'renovationYear': 'Renovation Year',
        'noOfFloors': 'Number of Floors',
        'handicapRooms': 'Handicap Rooms',
        'smokingHotel': 'Smoking Hotel',
        'smokingRooms': 'Smoking Rooms',
        'closingPeriod': 'Closing Period',
        'closedFrom': 'Closed From',
        'closedTo': 'Closed To',
        'function': 'Function',
        'companyLogoType': 'Company Logotype',
        'noCompanyLogo': 'You don’t have any logotype uploaded to this company',
        'emailAccountsNote': 'Property System User E-mail Accounts',
        'campaign': 'Campaign',
        'survey': 'Survey',
        'general': 'General',
        'currencies': 'Currencies',
        'exchangeRates': 'Exchange Rates',
        'propertyCurrencies': 'Property Currencies',
        'currenciesCantChange': 'You can’t edit the Base Currency after saved',
        'warnings': 'Warnings',
        'exchangeRatesForCurrencies': 'Exchange Rates of the Property',
        'exchangeType': 'Exchange Type',
        'exchangeRate': 'Exchange Rate',
        'isTheBaseCurrency': 'is the Base Currency of this Property',
        'userProfile': 'User Profile',
        'properties': 'Properties',
        'CreditCards': 'Credit Cards',
        'numberView': 'Number of views',
        'login': 'Login',
        'change': 'Change',
        'passwordHint': 'Password Hint',
        'changePassword': 'Change Password',
        'currentPassword': 'Current Password',
        'newPassword': 'New Password',
        'confirmNewPassword': 'Confirm New Password',
        'generate': 'Generate',
        'listProperties': 'List of Properties',
        'assignedProperties': 'Assigned Properties',
        'newCodeGenerated': 'New code generated succesfully',
        'toAuthenticateUser': 'To authenticate user',
        'followingOption': 'please use one of the following options',
        'rateNAvaibality': 'Update Rates/Packages & Availability',
        'removeRestrictions': 'Remove Restrictions',
        'maximumDays': 'Maximum Days',
        'keepCurrentSettings': 'Keep current settings',
        'stayThrough': 'Stay Through',
        'releaseDays': 'Release Days',
        'closedOnArrival': 'Closed On Arrival',
        'weekDays': 'Week Days',
        'closedDeparture': 'Closed On Departure',
        'closeSales': 'Close Sales',
        'openSales': 'Open Sales',
        'channels': 'Channels',
        'operators': 'Operators',
        'updatedSuccessfully': 'Updated successfully',
        'usingCurrentPrices': 'New Update using current prices',
        'newUpadate': 'New Upadate',
        'periodsAdded': 'no periods added',
        'noRatesPackages': 'no rates or packages added',
        'noRoomTypes': 'no room types added',
        'weekdays': 'Weekdays',
        'allotment': 'Allotment',
        'action': 'Action',
        'groupBy': 'Group by',
        'rate': 'Rate',
        'room': 'Room',
        'channel': 'Channel',
        'loyaltyProgram': 'Loyalty Program',
        'allRatesPackages': 'Select all Rates & Packages',
        'rates': 'Rates',
        'packages': 'Packages',
        'noPackageAvailable': 'No package available',
        'selectAllRates': 'Select all Rates',
        'mobilePackages': 'Mobile Packages',
        'bestAvailableRate': 'Best Available Rate',
        'addRoomTypes': 'Add Room Types',
        'clearSearch': 'Clear Search',
        'multiPageGridWithAutomaticBreakinglabel': 'Multi-page grid with automatic page breaking',
        'mainDetails': 'Main Details',
        'plsUseofFollowingOptions': 'please use one of the following options',
        'qRCode': 'QR Code',
        'transmitTheFollowingCodeToTheUser': 'Transmit the following code to the user',
        'transmitCodeToUser': 'Transmit the following code to the user',
        'scanOnPhone': 'Scan on the Users Smartphone',
        'sendSMS': 'Send code to the user by SMS',
        'commonInventory': 'Inventory',
        'commonUpdate': 'Update',
        'SetTotalRoomByPeriods': 'Set Total Room By Periods',
        'commonAvailable': 'Available',
        'commonOccupied': 'Occupied',
        'commonWeek': 'Week ',
        'commonMonth': 'Month',
        'commonSimpleView': 'Simple View',
        'commonDetailedView': 'Detailed view',
        'commonTotalRooms': 'Total Rooms',
        'commonRoomType': 'Room Type',
        'AllotmentC': 'Allotment C',
        'commonTotal': 'Total',
        'RoomAvailability': 'Room Availability',
        'RoomOccupation': 'Room Occupation',
        'LowAvailability': 'Low Availability',
        'CriticalAvailability': 'Critical Availability',
        'commonToday': 'Today',
        'LowAvailabilityCount': 'between 2 and 4',
        'CriticalAvailabilityCount': 'Less or equal 1',
        'UpdateAvailability': 'Update Availability',
        'UpdateOccupancy': 'Update Occupancy',
        'UpdateSecondaryText': 'Select Dates and Room Types to set the number of rooms',
        'SetGridTitle': 'Set the Number of Rooms',
        'commonDates': 'Dates',
        'AddPeriods': 'Add Periods',
        'AddRoomTypes': 'Add Room Types',
        'PeriodsOfDates': 'Periods of Dates',
        'commonFrom': 'From',
        'commonTo': 'To',
        'AvailableRooms': 'Available Rooms',
        'OccupiedRooms': 'Occupied Rooms',
        'AndMore': 'And more',
        'commonAvailability': 'Availability',
        'commonOccupancy': 'Occupancy',
        'totalRoomByPeriod': 'Set Total Rooms by Period',
        'selectRoomType': 'Select Room Type to Update',
        'setTotalNumOfRoomPerPeriod': 'Set the total number of rooms per period for',
        'setTotNumOfRoomPerPeriod': 'Set Total Rooms per Period',
        'setTotalNumOfRoomPerPeriodTo': 'Set the total number of rooms per period to',
        'UpdateRooms': 'Update Rooms',
        'commonAddNew': 'Add new',
        'code': 'code',
        'sendCodetotheUser': 'Send code to the user by SMS',
        'sendSMSlabel': 'Send SMS',
        'ReplicateProperty': 'Replicate Property',
        'ReplicateTo': 'Replicate to',
        'commonCopy': 'Copy',
        'BookingEngine': 'Booking Engine',
        'Policies': 'Policies',
        'OtherPolicies': 'Other Policies',
        'DepositPolicies': 'Deposit Policies',
        'Multimedia': 'Multimedia',
        'Activities': 'Activities',
        'RateTiers': 'Rate Tiers',
        'CalendarEvents': 'Calendar Events',
        'commonItems': 'items',
        'commonPágina': 'Page',
        'removedUsers': 'Removed Users',
        'newPropertyConform': 'Do you want to change for the new property?',
        'availability': 'Availability',
        'security': 'Security',
        'availabilityType': 'Availability Type',
        'mixed': 'Mixed',
        'availabilityManagement': 'Availability Management',
        'returnAvailability': 'Return availability',
        'availableInventory': 'Distribute all of the available inventory.',
        'availableInventoryRate': 'Distribute according to the alloment of the rate, regardless of the available inventory.',
        'availabilityTypeForRate': 'Availability type per room or rate will be configured at the rate level.',
        'increaseAvailability': 'Will increase availability in case of booking cancellation',
        'securitySettings': 'Credit card security settings',
        'protectedCreditCard': 'Protected credit card',
        'provideCreditCardDetails': 'Provide credit card details',
        'activeProtectedCreditCard': 'Activate protected credit card with CVC.',
        'creditCardDetails': 'Show credit card details on the booking print-out.',
        'saveSuccessfully': 'Save successfully',
        'generalSettings': 'General Settings',
        'newRoomType': 'New Room Type',
        'listOfPhotos': 'List Of Photos',
        'newIncentive': 'New Incentive',
        'dragAndDrop': 'Drag & Drop the roles from the list on the left to assign roles',
        'noItemsAssociated': 'No items assigned',
        'minLenghtError': 'Minimum length of the field is ',
        'passwordFormatError': 'should contain 8 digits including 1 uppercase letter, 1 lower case letter, 1 number',
        'invalid': 'invalid',
        'specialCharacterError': 'The values for special Charecter are not allow',
        'invalidFormatError': 'The value should be in proper format',
        'minValueError': 'The values allow Only more then 0',
        'phoneFormatError': 'Phone number should be in numeric with leading +',
        'matchPasswordError': 'Both Values Should be same',
        'invalidKeyword': 'contain some invalid keyword',
        'noMoreItemsMessage': 'You don´t have any more items',
        'inactivateClient': 'Inactivate Client',
        'activateClient': 'Activate Client',
        'commonNoFolderSelected': 'No Folder Selected!',
        'selectFolderToEditPhotos': 'Select a folder to check and edit your files',
        'uploadingPhotos': 'Uploading Photos',
        'pleaseSelectType': 'Please Select Type',
        'pleaseSelect': 'Please Select',
        'changeRoomOccupancy': 'Change room occupancy?',
        'changeRoomOccupancyMessage': 'When you modify the occupation to accept "field_changed", you must update the rates to include corresponding pricing information.',
        'invalidLat': 'Latitude should be between -90 and 90',
        'invalidLng': 'Longitude should be between -180 and 180',
        'applyExchangeRates': 'Apply exchange rates automatically',
        'defineExchangeRates': 'Define the Specific Exchange Rates',
};
